### ISSUE TITLE
官网上各组件、模块、模板展示页面的查看代码跳转链接为github的404页面

### ISSUE THREAD

**Issue by hu-qi** [alibaba-fusion/materials#1]
## 问题描述

【非技术性问题】[官网](https://fusion.design)各组件、模块、模板等页面的`查看代码`按钮跳转到github的404页面，另外有些查看代码的按钮指向url为空。

## 错误信息
如图，点击`查看代码`按钮跳转到github的404页面
![2](https://user-images.githubusercontent.com/17986122/50428574-c5cafb00-08f3-11e9-802c-5bd0653378e2.gif)

## 解决建议
经对比，是路径缺少react-materials这一层级。
e.g
错误链接：https://github.com/alibaba-fusion/materials/tree/master/scaffolds/next-single-page
正确链接：https://github.com/alibaba-fusion/materials/tree/master/react-materials/scaffolds/next-single-page
对于空白链接，建议补充完善！
感谢开源分享！
以上，非技术性问题，如非必要，请忽略。

**Comment by bindoon** [comment]
感谢反馈，404 已经 fix了，去掉了 react-materials
