### ISSUE TITLE
scaffold-lite-js 模板 install 时没有安装 react-router 依赖

### ISSUE THREAD

**Issue by FuzzyFade** [alibaba-fusion/materials#126]
RT
![image](https://user-images.githubusercontent.com/25416941/127865864-62bedc64-20ec-4596-89f8-16f57622f742.png)
手动安装 react-router 后才可正常启动该模板
ice verison: 1.18.3
yarn version: 1.22.10

**Comment by imsobear** [comment]
重复问题：https://github.com/alibaba/ice/issues/4569
