### ISSUE TITLE
build-plugin-fusion这个插件是不是都不生效了

### ISSUE THREAD

**Issue by xiazefeng** [alibaba-fusion/materials#136]
![image](https://user-images.githubusercontent.com/47770130/147727343-92e6990c-45f2-4068-a3bd-07b8ab51916d.png)
刚下的默认工程
如图所示，配置了一点作用都没

**Comment by imsobear** [comment]
https://ice.work/docs/plugin/list/fusion/#%E4%BD%BF%E7%94%A8-sass-%E5%8F%98%E9%87%8F%E5%AE%9A%E5%88%B6%E4%B8%BB%E9%A2%98%EF%BC%88%E4%B8%8D%E6%8E%A8%E8%8D%90%EF%BC%89
