### ISSUE TITLE
 Fusion Design Pro(TS)模板start失败

### ISSUE THREAD

**Issue by we6288815** [alibaba-fusion/materials#137]
通过AppWorks初始化 Fusion Design Pro(TS)模板，安装完成依赖后，执行npm start，启动失败，尝试了几次都不行，使用Lite模板是可以正常启动的。
麻烦看下是什么情况，谢谢。

相关日志如下:

> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   'd:\\nvm\\nodejs\\node.exe',
> 1 verbose cli   'd:\\nvm\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'start'
> 1 verbose cli ]
> 2 info using npm@6.14.13
> 3 info using node@v14.17.3
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle empm-frontend@0.1.0~prestart: empm-frontend@0.1.0
> 6 info lifecycle empm-frontend@0.1.0~start: empm-frontend@0.1.0
> 7 verbose lifecycle empm-frontend@0.1.0~start: unsafe-perm in lifecycle true
> 8 verbose lifecycle empm-frontend@0.1.0~start: PATH: D:\nvm\v14.17.3\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\work\workspace\IceProjects\empm-frontend\node_modules\.bin;C:\Programs\Python\Python37\Scripts\;C:\Programs\Python\Python37\;C:\Users\N.Liu\.jdks\jdk-17\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Tomcat\apache-tomcat-8.0.47\bin;C:\WINDOWS\System32\OpenSSH\;C:\maven\apache-maven-3.3.9\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files (x86)\Webex\Webex\Applications;C:\work\apache-maven-3.8.1\bin;d:\Program Files\Git\cmd;D:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;D:\Program Files\Amazon\AWSSAMCLI\bin\;D:\nvm;d:\nvm\nodejs;D:\Program Files (x86)\Yarn\bin\;C:\Program Files (x86)\OpenSSL-Win32\bin;D:\Android\Sdk\platform-tools;C:\Users\N.Liu\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;D:\Program Files\Microsoft VS Code\bin;C:\Users\N.Liu\AppData\Local\GitHubDesktop\bin;D:\Program Files\Fiddler
> 9 verbose lifecycle empm-frontend@0.1.0~start: CWD: C:\work\workspace\IceProjects\empm-frontend
> 10 silly lifecycle empm-frontend@0.1.0~start: Args: [ '/d /s /c', 'icejs start' ]
> 11 silly lifecycle empm-frontend@0.1.0~start: Returned: code: 1  signal: null
> 12 info lifecycle empm-frontend@0.1.0~start: Failed to exec start script
> 13 verbose stack Error: empm-frontend@0.1.0 start: `icejs start`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (D:\nvm\v14.17.3\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:375:28)
> 13 verbose stack     at ChildProcess.<anonymous> (D:\nvm\v14.17.3\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:375:28)
> 13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
> 14 verbose pkgid empm-frontend@0.1.0
> 15 verbose cwd C:\work\workspace\IceProjects\empm-frontend
> 16 verbose Windows_NT 10.0.19042
> 17 verbose argv "d:\\nvm\\nodejs\\node.exe" "d:\\nvm\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
> 18 verbose node v14.17.3
> 19 verbose npm  v6.14.13
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error empm-frontend@0.1.0 start: `icejs start`
> 22 error Exit status 1
> 23 error Failed at the empm-frontend@0.1.0 start script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]ndows_NT 10.0.19042
> 17 verbose argv "d:\\nvm\\nodejs\\node.exe" "d:\\nvm\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
> 18 verbose node v14.17.3
> 19 verbose npm  v6.14.13
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error empm-frontend@0.1.0 start: `icejs start`
> 22 error Exit status 1
> 23 error Failed at the empm-frontend@0.1.0 start script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
>

**Comment by we6288815** [comment]
把build.json里的"vite": true改为"vite": false可以正常启动

**Comment by luhc228** [comment]
开启 vite 后，在 windows 环境下没有复现上面的错误

**Comment by we6288815** [comment]
> 开启 vite 后，在 windows 环境下没有复现上面的错误

目前参考这个issue临时解决
[https://github.com/alibaba/ice/issues/5054](url)

**Comment by imsobear** [comment]
重复问题。
