### ISSUE TITLE
ice-stark-layout运行在IE11时报错 SCRIPT5022: Objects are not valid as a React child

### ISSUE THREAD

**Issue by BestDI** [alibaba-fusion/materials#19]
你好，直接下载运行 `ice-stark-layout` 工程时报错，且页面空白：

![image](https://user-images.githubusercontent.com/19953784/78736573-0e3ee880-7980-11ea-9ab8-ed0b2f1266af.png)

盼复~
🚶 🚶‍♀

**Comment by ClarkXia** [comment]
在 https://github.com/ice-lab/icestark/issues/108 跟进
