### ISSUE TITLE
物料启动不起来

### ISSUE THREAD

**Issue by cabinhero** [alibaba-fusion/materials#24]
按照文档操作
1、根目录下npm install
2、cd blocks/AdvancedDetail
3、 npm install
4、 npm run start
报错如下：
![image](https://user-images.githubusercontent.com/31085313/81395940-1775cd80-9157-11ea-8b3d-ddfda8c5d85c.png)

**Comment by imsobear** [comment]
windows 下的路径兼容问题，自行改成 windows 下的路径格式即可。
