### ISSUE TITLE
有没有接口、路由等配置文件快速生成的方案

### ISSUE THREAD

**Issue by tyuqing** [alibaba-fusion/materials#90]
大家好，有没有接口、路由等配置文件快速生成的最佳实践方案。

我看到可以通过飞冰在工程中某个文件夹下快速生成页面相关的主体逻辑。可是一个功能的完成除了这些主体逻辑以外，还包括很多，比如请求接口，路由的配置或页面在菜单中的入口等等，这个代码会分散在工程的各个文件夹中，所以我现在无法在物料的模板中完成。

以“请求接口”为例，我看到官网物料的数据请求是将接口逻辑直接写在组件中（如[代码](https://github.com/alibaba-fusion/materials/blob/master/pages/QueryTable/src/index.tsx.ejs#L35)）。我希望能将接口维护在单独的文件中，并且这些代码能快速生成。以场景列表物料为例，场景列表的接口希望维护在如下文件中：

``` JavaScript
// 文件 src/api/scene.js
import request from './base.js';
export function getSceneList(params) {
  return request.get('/api/scene/list', { params });
}
```

**Comment by tyuqing** [comment]
上面提到的问题 我是这样实现的：将会分散在其他文件的代码 在物料模板加了readme来实现的，使用者按照readme中提供的内容完成后续功能。[示例代码](https://github.com/codeless-js/vue-materials-iview/blob/master/pages/QueryTable/src/readme.md.ejs)。我觉得不太智能，希望跟大家探讨。

**Comment by brizer** [comment]
> 上面提到的问题 我是这样实现的：将会分散在其他文件的代码 在物料模板加了readme来实现的，使用者按照readme中提供的内容完成后续功能。[示例代码](https://github.com/codeless-js/vue-materials-iview/blob/master/pages/QueryTable/src/readme.md.ejs)。我觉得不太智能，希望跟大家探讨。

看起来没人探讨

**Comment by imsobear** [comment]
@tyuqing @brizer 建议在这个仓库提 issue 讨论：https://github.com/alibaba/ice

**Comment by tyuqing** [comment]
> @tyuqing @brizer 建议在这个仓库提 issue 讨论：https://github.com/alibaba/ice

好的，感谢。

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/issues/4596
